language: rust
rust:
 - 1.11.0
 - nightly
 - beta
 - stable

os:
  - linux
  - osx

script:
 - cargo test
 - "[ $TRAVIS_RUST_VERSION != nightly ] || cargo test --features unstable"
 - "[[ $TRAVIS_RUST_VERSION != nightly && $TRAVIS_RUST_VERSION != beta ]] || cargo test --manifest-path derive/Cargo.toml"

